name: build

on:
  pull_request:
    branches: [ main, develop, features/* ]
    paths-ignore:
    - 'README.md'

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-test:
    name: Build and test
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

